#!/bin/bash

compton &
xfce4-power-manager &
feh --bg-fill ~/Pictures/wallpapers/VGFwZXMK.jpg &
sxhkd -c ~/.config/berry/sxhkdrc &
python -m SimpleHTTPServer 8085 &
bash ~/.config/lemonbar/config.sh | bash ~/.config/lemonbar/lemonbar.sh &

# Set decoration geometry
berryc border_width       3
berryc inner_border_width 0
berryc title_height       0
berryc top_gap            20

# Set decoration colors
berryc focus_color         647196
berryc unfocus_color       292D3E
berryc inner_focus_color   FFCB6B
berryc inner_unfocus_color 565679
berryc text_focus_color    ffffff
berryc text_unfocus_color  eeeeee

# Other options
berryc smart_place "false"
berryc draw_text   "true"
berryc edge_lock   "true"
