#!/bin/bash

sxhkd -c /home/taz/.config/berry/sxhkdrc &
picom &

# Set decoration geometry
berryc border_width       3
berryc inner_border_width 0
berryc title_height       0
berryc top_gap            0

# Set decoration colors
berryc focus_color         292D3E
berryc unfocus_color       292D3E
berryc inner_focus_color   FFCB6B
berryc inner_unfocus_color 565679
berryc text_focus_color    ffffff
berryc text_unfocus_color  eeeeee

# Other options
berryc smart_place "false"
berryc draw_text   "false"
berryc edge_lock   "true"
berryc set_font    "Dina-9"
